//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cantones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cantones()
        {
            this.Matriculas = new HashSet<Matriculas>();
        }
    
        public int can_id { get; set; }
        public Nullable<byte> pro_id { get; set; }
        public string can_nombre { get; set; }
        public string can_status { get; set; }
        public System.DateTime can_add { get; set; }
        public Nullable<System.DateTime> can_update { get; set; }
        public Nullable<System.DateTime> can_delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matriculas> Matriculas { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
