//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Base_Matriculacion_VehiculosEntities : DbContext
    {
        public Base_Matriculacion_VehiculosEntities()
            : base("name=Base_Matriculacion_VehiculosEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cantones> Cantones { get; set; }
        public virtual DbSet<ClLASes> ClLASes { get; set; }
        public virtual DbSet<Colores> Colores { get; set; }
        public virtual DbSet<Discapacidades> Discapacidades { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Matriculas> Matriculas { get; set; }
        public virtual DbSet<MODELos> MODELos { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Discapacidades> Tipo_Discapacidades { get; set; }
        public virtual DbSet<Tipos> Tipos { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
    }
}
