//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Discapacidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Discapacidades()
        {
            this.Discapacidades = new HashSet<Discapacidades>();
        }
    
        public byte tdi_id { get; set; }
        public string tdi_descripcion { get; set; }
        public string tdi_status { get; set; }
        public System.DateTime tdi_add { get; set; }
        public Nullable<System.DateTime> tdi_update { get; set; }
        public Nullable<System.DateTime> tdi_delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discapacidades> Discapacidades { get; set; }
    }
}
