//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int us_id { get; set; }
        public string us_correo { get; set; }
        public string us_password { get; set; }
        public string us_apellido { get; set; }
        public string us_nombres { get; set; }
        public string us_estatus { get; set; }
        public Nullable<int> us_intentos { get; set; }
        public Nullable<System.DateTime> us_fechaInten { get; set; }
        public Nullable<int> rol_id { get; set; }
        public System.DateTime us_add { get; set; }
        public Nullable<System.DateTime> us_update { get; set; }
        public Nullable<System.DateTime> us_delete { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
